services:
  web:
    volumes:
      - "./nginx/localhost.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    ports:
      - "${PROXY_PORT_NGINX_HTTP:-8000}:80"

  php:
    build:
      dockerfile: Dockerfile
      target: dev
    container_name: harangiert_php
    volumes:
      - "./app:/var/www/html"
    networks:
      default:
        aliases:
          - harangiert-php-fpm
    depends_on:
      - db
    env_file:
      - .env

  frankenphp:
    build:
      dockerfile: Dockerfile.frankenphp
      target: dev
    container_name: harangiert_frankenphp
    volumes:
      - ./app:/var/www/app
      - ./caddy/Caddyfile.local:/etc/frankenphp/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    ports:
      - "${PROXY_PORT_CADDY_HTTP:-8001}:80"
      - "${PROXY_PORT_CADDY_HTTPS:-4331}:443"
      - "${PROXY_PORT_CADDY_HTTPS:-4331}:443/udp"

  db:
    image: mariadb:10.11
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      default:
        aliases:
          - harangiert-db

volumes:
  caddy_data:
  caddy_config: