version: '3.2'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./app:/var/www/html"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    links:
      - php
  php:
    build:
      context: ./php
      target: ${PHP_ENV}
    restart: always
    volumes:
      - "./app:/var/www/html"
    networks:
      default:
        aliases:
          - harangiert-php-fpm
    links:
      - mariadb
  mariadb:
    image: mariadb:10.3
    ports:
      - "42000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./mariadb:/var/lib/mysql"
    networks:
      default:
        aliases:
          - harangiert-mariadb
  encore:
    image: node:14-alpine
    volumes:
      - "./app:/app"
    working_dir: /app
    command: ["yarn", "watch"]
