services:
  web:
    image: nginx:1.26-alpine
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    links:
      - php

  php:
    build:
      context: ./php
      target: ${PHP_ENV}
    container_name: harangiert_php
    volumes:
      - "./app:/var/www/html"
      - "./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    networks:
      default:
        aliases:
          - harangiert-php-fpm
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb:10.6
    ports:
      - "127.0.0.1:42000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./mariadb:/var/lib/mysql"
    networks:
      default:
        aliases:
          - harangiert-mariadb

  encore:
    image: node:20-alpine
    container_name: harangiert_encore
    volumes:
      - "./app:/app"
    working_dir: /app/assets/website
    command: ["yarn", "watch"]
