version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./app:/var/www/html"
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    links:
      - php
  php:
    build:
      context: ./php
    restart: always
    volumes:
      - "./app:/var/www/html"
    container_name: harangiert-php-fpm
    environment:
      - APP_DEBUG=1
    links:
      - mariadb
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./mariadb:/var/lib/mysql"
    container_name: harangiert-mariadb
  encore:
    image: node:10-alpine
    volumes:
      - "./app:/app"
    working_dir: /app
    container_name: harangiert-encore
    command: ["yarn", "encore", "dev", "--watch"]
