services:
  web:
    volumes:
      - "./nginx/localhost.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    ports:
      - "127.0.0.1:${PROXY_PORT:-8000}:80"

  php:
    build:
      dockerfile: Dockerfile
      target: dev
    container_name: harangiert_php
    volumes:
      - "./app:/var/www/html"
    networks:
      default:
        aliases:
          - harangiert-php-fpm
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.11@sha256:8020e05c4c498d06c87f0a1db010eb79bd6f8fb30e9b763d4690c34ce1e61008
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      default:
        aliases:
          - harangiert-db
